#pragma once
#include "imxrt.h"
#include "pins_arduino.h"

#define FLASH_BASEADDR       0x601F0000
#define FLASH_SIZE           0x00200000
#define FLASH_SECTORS        15        
#define FLASH_EEPROM_ENDADDR 0x437     

#define CORE_NUM_TOTAL_PINS 40
#define CORE_NUM_DIGITAL    40
#define CORE_NUM_INTERRUPT  40
#define CORE_NUM_ANALOG     14
#define CORE_NUM_PWM        31

#define CORE_PIN0_BIT  3 
#define CORE_PIN1_BIT  2 
#define CORE_PIN2_BIT  4 
#define CORE_PIN3_BIT  5 
#define CORE_PIN4_BIT  6 
#define CORE_PIN5_BIT  8 
#define CORE_PIN6_BIT  10
#define CORE_PIN7_BIT  17
#define CORE_PIN8_BIT  16
#define CORE_PIN9_BIT  11
#define CORE_PIN10_BIT 0 
#define CORE_PIN11_BIT 2 
#define CORE_PIN12_BIT 1 
#define CORE_PIN13_BIT 3 
#define CORE_PIN14_BIT 18
#define CORE_PIN15_BIT 19
#define CORE_PIN16_BIT 23
#define CORE_PIN17_BIT 22
#define CORE_PIN18_BIT 17
#define CORE_PIN19_BIT 16
#define CORE_PIN20_BIT 26
#define CORE_PIN21_BIT 27
#define CORE_PIN22_BIT 24
#define CORE_PIN23_BIT 25
#define CORE_PIN24_BIT 12
#define CORE_PIN25_BIT 13
#define CORE_PIN26_BIT 30
#define CORE_PIN27_BIT 31
#define CORE_PIN28_BIT 18
#define CORE_PIN29_BIT 31
#define CORE_PIN30_BIT 23
#define CORE_PIN31_BIT 22
#define CORE_PIN32_BIT 12
#define CORE_PIN33_BIT 7 
#define CORE_PIN34_BIT 15
#define CORE_PIN35_BIT 14
#define CORE_PIN36_BIT 13
#define CORE_PIN37_BIT 12
#define CORE_PIN38_BIT 17
#define CORE_PIN39_BIT 16


#define CORE_PIN0_BITMASK  (1<<(CORE_PIN0_BIT)) 
#define CORE_PIN1_BITMASK  (1<<(CORE_PIN1_BIT)) 
#define CORE_PIN2_BITMASK  (1<<(CORE_PIN2_BIT)) 
#define CORE_PIN3_BITMASK  (1<<(CORE_PIN3_BIT)) 
#define CORE_PIN4_BITMASK  (1<<(CORE_PIN4_BIT)) 
#define CORE_PIN5_BITMASK  (1<<(CORE_PIN5_BIT)) 
#define CORE_PIN6_BITMASK  (1<<(CORE_PIN6_BIT)) 
#define CORE_PIN7_BITMASK  (1<<(CORE_PIN7_BIT)) 
#define CORE_PIN8_BITMASK  (1<<(CORE_PIN8_BIT)) 
#define CORE_PIN9_BITMASK  (1<<(CORE_PIN9_BIT)) 
#define CORE_PIN10_BITMASK (1<<(CORE_PIN10_BIT))
#define CORE_PIN11_BITMASK (1<<(CORE_PIN11_BIT))
#define CORE_PIN12_BITMASK (1<<(CORE_PIN12_BIT))
#define CORE_PIN13_BITMASK (1<<(CORE_PIN13_BIT))
#define CORE_PIN14_BITMASK (1<<(CORE_PIN14_BIT))
#define CORE_PIN15_BITMASK (1<<(CORE_PIN15_BIT))
#define CORE_PIN16_BITMASK (1<<(CORE_PIN16_BIT))
#define CORE_PIN17_BITMASK (1<<(CORE_PIN17_BIT))
#define CORE_PIN18_BITMASK (1<<(CORE_PIN18_BIT))
#define CORE_PIN19_BITMASK (1<<(CORE_PIN19_BIT))
#define CORE_PIN20_BITMASK (1<<(CORE_PIN20_BIT))
#define CORE_PIN21_BITMASK (1<<(CORE_PIN21_BIT))
#define CORE_PIN22_BITMASK (1<<(CORE_PIN22_BIT))
#define CORE_PIN23_BITMASK (1<<(CORE_PIN23_BIT))
#define CORE_PIN24_BITMASK (1<<(CORE_PIN24_BIT))
#define CORE_PIN25_BITMASK (1<<(CORE_PIN25_BIT))
#define CORE_PIN26_BITMASK (1<<(CORE_PIN26_BIT))
#define CORE_PIN27_BITMASK (1<<(CORE_PIN27_BIT))
#define CORE_PIN28_BITMASK (1<<(CORE_PIN28_BIT))
#define CORE_PIN29_BITMASK (1<<(CORE_PIN29_BIT))
#define CORE_PIN30_BITMASK (1<<(CORE_PIN30_BIT))
#define CORE_PIN31_BITMASK (1<<(CORE_PIN31_BIT))
#define CORE_PIN32_BITMASK (1<<(CORE_PIN32_BIT))
#define CORE_PIN33_BITMASK (1<<(CORE_PIN33_BIT))
#define CORE_PIN34_BITMASK (1<<(CORE_PIN34_BIT))
#define CORE_PIN35_BITMASK (1<<(CORE_PIN35_BIT))
#define CORE_PIN36_BITMASK (1<<(CORE_PIN36_BIT))
#define CORE_PIN37_BITMASK (1<<(CORE_PIN37_BIT))
#define CORE_PIN38_BITMASK (1<<(CORE_PIN38_BIT))
#define CORE_PIN39_BITMASK (1<<(CORE_PIN39_BIT))


#define CORE_PIN0_PORTREG  GPIO6_DR
#define CORE_PIN1_PORTREG  GPIO6_DR
#define CORE_PIN2_PORTREG  GPIO9_DR
#define CORE_PIN3_PORTREG  GPIO9_DR
#define CORE_PIN4_PORTREG  GPIO9_DR
#define CORE_PIN5_PORTREG  GPIO9_DR
#define CORE_PIN6_PORTREG  GPIO7_DR
#define CORE_PIN7_PORTREG  GPIO7_DR
#define CORE_PIN8_PORTREG  GPIO7_DR
#define CORE_PIN9_PORTREG  GPIO7_DR
#define CORE_PIN10_PORTREG GPIO7_DR
#define CORE_PIN11_PORTREG GPIO7_DR
#define CORE_PIN12_PORTREG GPIO7_DR
#define CORE_PIN13_PORTREG GPIO7_DR
#define CORE_PIN14_PORTREG GPIO6_DR
#define CORE_PIN15_PORTREG GPIO6_DR
#define CORE_PIN16_PORTREG GPIO6_DR
#define CORE_PIN17_PORTREG GPIO6_DR
#define CORE_PIN18_PORTREG GPIO6_DR
#define CORE_PIN19_PORTREG GPIO6_DR
#define CORE_PIN20_PORTREG GPIO6_DR
#define CORE_PIN21_PORTREG GPIO6_DR
#define CORE_PIN22_PORTREG GPIO6_DR
#define CORE_PIN23_PORTREG GPIO6_DR
#define CORE_PIN24_PORTREG GPIO6_DR
#define CORE_PIN25_PORTREG GPIO6_DR
#define CORE_PIN26_PORTREG GPIO6_DR
#define CORE_PIN27_PORTREG GPIO6_DR
#define CORE_PIN28_PORTREG GPIO8_DR
#define CORE_PIN29_PORTREG GPIO9_DR
#define CORE_PIN30_PORTREG GPIO8_DR
#define CORE_PIN31_PORTREG GPIO8_DR
#define CORE_PIN32_PORTREG GPIO7_DR
#define CORE_PIN33_PORTREG GPIO9_DR
#define CORE_PIN34_PORTREG GPIO8_DR
#define CORE_PIN35_PORTREG GPIO8_DR
#define CORE_PIN36_PORTREG GPIO8_DR
#define CORE_PIN37_PORTREG GPIO8_DR
#define CORE_PIN38_PORTREG GPIO8_DR
#define CORE_PIN39_PORTREG GPIO8_DR


#define CORE_PIN0_PORTSET  GPIO6_DR_SET
#define CORE_PIN1_PORTSET  GPIO6_DR_SET
#define CORE_PIN2_PORTSET  GPIO9_DR_SET
#define CORE_PIN3_PORTSET  GPIO9_DR_SET
#define CORE_PIN4_PORTSET  GPIO9_DR_SET
#define CORE_PIN5_PORTSET  GPIO9_DR_SET
#define CORE_PIN6_PORTSET  GPIO7_DR_SET
#define CORE_PIN7_PORTSET  GPIO7_DR_SET
#define CORE_PIN8_PORTSET  GPIO7_DR_SET
#define CORE_PIN9_PORTSET  GPIO7_DR_SET
#define CORE_PIN10_PORTSET GPIO7_DR_SET
#define CORE_PIN11_PORTSET GPIO7_DR_SET
#define CORE_PIN12_PORTSET GPIO7_DR_SET
#define CORE_PIN13_PORTSET GPIO7_DR_SET
#define CORE_PIN14_PORTSET GPIO6_DR_SET
#define CORE_PIN15_PORTSET GPIO6_DR_SET
#define CORE_PIN16_PORTSET GPIO6_DR_SET
#define CORE_PIN17_PORTSET GPIO6_DR_SET
#define CORE_PIN18_PORTSET GPIO6_DR_SET
#define CORE_PIN19_PORTSET GPIO6_DR_SET
#define CORE_PIN20_PORTSET GPIO6_DR_SET
#define CORE_PIN21_PORTSET GPIO6_DR_SET
#define CORE_PIN22_PORTSET GPIO6_DR_SET
#define CORE_PIN23_PORTSET GPIO6_DR_SET
#define CORE_PIN24_PORTSET GPIO6_DR_SET
#define CORE_PIN25_PORTSET GPIO6_DR_SET
#define CORE_PIN26_PORTSET GPIO6_DR_SET
#define CORE_PIN27_PORTSET GPIO6_DR_SET
#define CORE_PIN28_PORTSET GPIO8_DR_SET
#define CORE_PIN29_PORTSET GPIO9_DR_SET
#define CORE_PIN30_PORTSET GPIO8_DR_SET
#define CORE_PIN31_PORTSET GPIO8_DR_SET
#define CORE_PIN32_PORTSET GPIO7_DR_SET
#define CORE_PIN33_PORTSET GPIO9_DR_SET
#define CORE_PIN34_PORTSET GPIO8_DR_SET
#define CORE_PIN35_PORTSET GPIO8_DR_SET
#define CORE_PIN36_PORTSET GPIO8_DR_SET
#define CORE_PIN37_PORTSET GPIO8_DR_SET
#define CORE_PIN38_PORTSET GPIO8_DR_SET
#define CORE_PIN39_PORTSET GPIO8_DR_SET


#define CORE_PIN0_PORTCLEAR  GPIO6_DR_CLEAR
#define CORE_PIN1_PORTCLEAR  GPIO6_DR_CLEAR
#define CORE_PIN2_PORTCLEAR  GPIO9_DR_CLEAR
#define CORE_PIN3_PORTCLEAR  GPIO9_DR_CLEAR
#define CORE_PIN4_PORTCLEAR  GPIO9_DR_CLEAR
#define CORE_PIN5_PORTCLEAR  GPIO9_DR_CLEAR
#define CORE_PIN6_PORTCLEAR  GPIO7_DR_CLEAR
#define CORE_PIN7_PORTCLEAR  GPIO7_DR_CLEAR
#define CORE_PIN8_PORTCLEAR  GPIO7_DR_CLEAR
#define CORE_PIN9_PORTCLEAR  GPIO7_DR_CLEAR
#define CORE_PIN10_PORTCLEAR GPIO7_DR_CLEAR
#define CORE_PIN11_PORTCLEAR GPIO7_DR_CLEAR
#define CORE_PIN12_PORTCLEAR GPIO7_DR_CLEAR
#define CORE_PIN13_PORTCLEAR GPIO7_DR_CLEAR
#define CORE_PIN14_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN15_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN16_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN17_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN18_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN19_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN20_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN21_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN22_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN23_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN24_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN25_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN26_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN27_PORTCLEAR GPIO6_DR_CLEAR
#define CORE_PIN28_PORTCLEAR GPIO8_DR_CLEAR
#define CORE_PIN29_PORTCLEAR GPIO9_DR_CLEAR
#define CORE_PIN30_PORTCLEAR GPIO8_DR_CLEAR
#define CORE_PIN31_PORTCLEAR GPIO8_DR_CLEAR
#define CORE_PIN32_PORTCLEAR GPIO7_DR_CLEAR
#define CORE_PIN33_PORTCLEAR GPIO9_DR_CLEAR
#define CORE_PIN34_PORTCLEAR GPIO8_DR_CLEAR
#define CORE_PIN35_PORTCLEAR GPIO8_DR_CLEAR
#define CORE_PIN36_PORTCLEAR GPIO8_DR_CLEAR
#define CORE_PIN37_PORTCLEAR GPIO8_DR_CLEAR
#define CORE_PIN38_PORTCLEAR GPIO8_DR_CLEAR
#define CORE_PIN39_PORTCLEAR GPIO8_DR_CLEAR


#define CORE_PIN0_PORTTOGGLE  GPIO6_DR_TOGGLE
#define CORE_PIN1_PORTTOGGLE  GPIO6_DR_TOGGLE
#define CORE_PIN2_PORTTOGGLE  GPIO9_DR_TOGGLE
#define CORE_PIN3_PORTTOGGLE  GPIO9_DR_TOGGLE
#define CORE_PIN4_PORTTOGGLE  GPIO9_DR_TOGGLE
#define CORE_PIN5_PORTTOGGLE  GPIO9_DR_TOGGLE
#define CORE_PIN6_PORTTOGGLE  GPIO7_DR_TOGGLE
#define CORE_PIN7_PORTTOGGLE  GPIO7_DR_TOGGLE
#define CORE_PIN8_PORTTOGGLE  GPIO7_DR_TOGGLE
#define CORE_PIN9_PORTTOGGLE  GPIO7_DR_TOGGLE
#define CORE_PIN10_PORTTOGGLE GPIO7_DR_TOGGLE
#define CORE_PIN11_PORTTOGGLE GPIO7_DR_TOGGLE
#define CORE_PIN12_PORTTOGGLE GPIO7_DR_TOGGLE
#define CORE_PIN13_PORTTOGGLE GPIO7_DR_TOGGLE
#define CORE_PIN14_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN15_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN16_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN17_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN18_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN19_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN20_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN21_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN22_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN23_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN24_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN25_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN26_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN27_PORTTOGGLE GPIO6_DR_TOGGLE
#define CORE_PIN28_PORTTOGGLE GPIO8_DR_TOGGLE
#define CORE_PIN29_PORTTOGGLE GPIO9_DR_TOGGLE
#define CORE_PIN30_PORTTOGGLE GPIO8_DR_TOGGLE
#define CORE_PIN31_PORTTOGGLE GPIO8_DR_TOGGLE
#define CORE_PIN32_PORTTOGGLE GPIO7_DR_TOGGLE
#define CORE_PIN33_PORTTOGGLE GPIO9_DR_TOGGLE
#define CORE_PIN34_PORTTOGGLE GPIO8_DR_TOGGLE
#define CORE_PIN35_PORTTOGGLE GPIO8_DR_TOGGLE
#define CORE_PIN36_PORTTOGGLE GPIO8_DR_TOGGLE
#define CORE_PIN37_PORTTOGGLE GPIO8_DR_TOGGLE
#define CORE_PIN38_PORTTOGGLE GPIO8_DR_TOGGLE
#define CORE_PIN39_PORTTOGGLE GPIO8_DR_TOGGLE


#define CORE_PIN0_DDRREG  GPIO6_GDIR
#define CORE_PIN1_DDRREG  GPIO6_GDIR
#define CORE_PIN2_DDRREG  GPIO9_GDIR
#define CORE_PIN3_DDRREG  GPIO9_GDIR
#define CORE_PIN4_DDRREG  GPIO9_GDIR
#define CORE_PIN5_DDRREG  GPIO9_GDIR
#define CORE_PIN6_DDRREG  GPIO7_GDIR
#define CORE_PIN7_DDRREG  GPIO7_GDIR
#define CORE_PIN8_DDRREG  GPIO7_GDIR
#define CORE_PIN9_DDRREG  GPIO7_GDIR
#define CORE_PIN10_DDRREG GPIO7_GDIR
#define CORE_PIN11_DDRREG GPIO7_GDIR
#define CORE_PIN12_DDRREG GPIO7_GDIR
#define CORE_PIN13_DDRREG GPIO7_GDIR
#define CORE_PIN14_DDRREG GPIO6_GDIR
#define CORE_PIN15_DDRREG GPIO6_GDIR
#define CORE_PIN16_DDRREG GPIO6_GDIR
#define CORE_PIN17_DDRREG GPIO6_GDIR
#define CORE_PIN18_DDRREG GPIO6_GDIR
#define CORE_PIN19_DDRREG GPIO6_GDIR
#define CORE_PIN20_DDRREG GPIO6_GDIR
#define CORE_PIN21_DDRREG GPIO6_GDIR
#define CORE_PIN22_DDRREG GPIO6_GDIR
#define CORE_PIN23_DDRREG GPIO6_GDIR
#define CORE_PIN24_DDRREG GPIO6_GDIR
#define CORE_PIN25_DDRREG GPIO6_GDIR
#define CORE_PIN26_DDRREG GPIO6_GDIR
#define CORE_PIN27_DDRREG GPIO6_GDIR
#define CORE_PIN28_DDRREG GPIO8_GDIR
#define CORE_PIN29_DDRREG GPIO9_GDIR
#define CORE_PIN30_DDRREG GPIO8_GDIR
#define CORE_PIN31_DDRREG GPIO8_GDIR
#define CORE_PIN32_DDRREG GPIO7_GDIR
#define CORE_PIN33_DDRREG GPIO9_GDIR
#define CORE_PIN34_DDRREG GPIO8_GDIR
#define CORE_PIN35_DDRREG GPIO8_GDIR
#define CORE_PIN36_DDRREG GPIO8_GDIR
#define CORE_PIN37_DDRREG GPIO8_GDIR
#define CORE_PIN38_DDRREG GPIO8_GDIR
#define CORE_PIN39_DDRREG GPIO8_GDIR


#define CORE_PIN0_PINREG  GPIO6_PSR
#define CORE_PIN1_PINREG  GPIO6_PSR
#define CORE_PIN2_PINREG  GPIO9_PSR
#define CORE_PIN3_PINREG  GPIO9_PSR
#define CORE_PIN4_PINREG  GPIO9_PSR
#define CORE_PIN5_PINREG  GPIO9_PSR
#define CORE_PIN6_PINREG  GPIO7_PSR
#define CORE_PIN7_PINREG  GPIO7_PSR
#define CORE_PIN8_PINREG  GPIO7_PSR
#define CORE_PIN9_PINREG  GPIO7_PSR
#define CORE_PIN10_PINREG GPIO7_PSR
#define CORE_PIN11_PINREG GPIO7_PSR
#define CORE_PIN12_PINREG GPIO7_PSR
#define CORE_PIN13_PINREG GPIO7_PSR
#define CORE_PIN14_PINREG GPIO6_PSR
#define CORE_PIN15_PINREG GPIO6_PSR
#define CORE_PIN16_PINREG GPIO6_PSR
#define CORE_PIN17_PINREG GPIO6_PSR
#define CORE_PIN18_PINREG GPIO6_PSR
#define CORE_PIN19_PINREG GPIO6_PSR
#define CORE_PIN20_PINREG GPIO6_PSR
#define CORE_PIN21_PINREG GPIO6_PSR
#define CORE_PIN22_PINREG GPIO6_PSR
#define CORE_PIN23_PINREG GPIO6_PSR
#define CORE_PIN24_PINREG GPIO6_PSR
#define CORE_PIN25_PINREG GPIO6_PSR
#define CORE_PIN26_PINREG GPIO6_PSR
#define CORE_PIN27_PINREG GPIO6_PSR
#define CORE_PIN28_PINREG GPIO8_PSR
#define CORE_PIN29_PINREG GPIO9_PSR
#define CORE_PIN30_PINREG GPIO8_PSR
#define CORE_PIN31_PINREG GPIO8_PSR
#define CORE_PIN32_PINREG GPIO7_PSR
#define CORE_PIN33_PINREG GPIO9_PSR
#define CORE_PIN34_PINREG GPIO8_PSR
#define CORE_PIN35_PINREG GPIO8_PSR
#define CORE_PIN36_PINREG GPIO8_PSR
#define CORE_PIN37_PINREG GPIO8_PSR
#define CORE_PIN38_PINREG GPIO8_PSR
#define CORE_PIN39_PINREG GPIO8_PSR


// mux config registers control which peripheral uses the pin
#define CORE_PIN0_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_03
#define CORE_PIN1_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_02
#define CORE_PIN2_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_04  
#define CORE_PIN3_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_05  
#define CORE_PIN4_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_06  
#define CORE_PIN5_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_08  
#define CORE_PIN6_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_B0_10   
#define CORE_PIN7_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_B1_01   
#define CORE_PIN8_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_B1_00   
#define CORE_PIN9_CONFIG  IOMUXC_SW_MUX_CTL_PAD_GPIO_B0_11   
#define CORE_PIN10_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_B0_00   
#define CORE_PIN11_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_B0_02   
#define CORE_PIN12_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_B0_01   
#define CORE_PIN13_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_B0_03   
#define CORE_PIN14_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_02
#define CORE_PIN15_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_03
#define CORE_PIN16_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_07
#define CORE_PIN17_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_06
#define CORE_PIN18_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_01
#define CORE_PIN19_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_00
#define CORE_PIN20_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_10
#define CORE_PIN21_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_11
#define CORE_PIN22_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_08
#define CORE_PIN23_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_09
#define CORE_PIN24_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_12
#define CORE_PIN25_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_13
#define CORE_PIN26_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_14
#define CORE_PIN27_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_15
#define CORE_PIN28_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_32  
#define CORE_PIN29_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_31  
#define CORE_PIN30_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_37  
#define CORE_PIN31_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_36  
#define CORE_PIN32_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_B0_12   
#define CORE_PIN33_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_07  
#define CORE_PIN34_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_03
#define CORE_PIN35_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_02
#define CORE_PIN36_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_01
#define CORE_PIN37_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_00
#define CORE_PIN38_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_05
#define CORE_PIN39_CONFIG IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_04


// pad config registers control pullup/pulldown/keeper, drive strength, etc
#define CORE_PIN0_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B0_03
#define CORE_PIN1_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B0_02
#define CORE_PIN2_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_04  
#define CORE_PIN3_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_05  
#define CORE_PIN4_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_06  
#define CORE_PIN5_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_08  
#define CORE_PIN6_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_B0_10   
#define CORE_PIN7_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_B1_01   
#define CORE_PIN8_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_B1_00   
#define CORE_PIN9_PADCONFIG  IOMUXC_SW_PAD_CTL_PAD_GPIO_B0_11   
#define CORE_PIN10_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_B0_00   
#define CORE_PIN11_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_B0_02   
#define CORE_PIN12_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_B0_01   
#define CORE_PIN13_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_B0_03   
#define CORE_PIN14_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_02
#define CORE_PIN15_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_03
#define CORE_PIN16_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_07
#define CORE_PIN17_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_06
#define CORE_PIN18_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_01
#define CORE_PIN19_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_00
#define CORE_PIN20_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_10
#define CORE_PIN21_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_11
#define CORE_PIN22_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_08
#define CORE_PIN23_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_09
#define CORE_PIN24_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B0_12
#define CORE_PIN25_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B0_13
#define CORE_PIN26_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_14
#define CORE_PIN27_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B1_15
#define CORE_PIN28_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_32  
#define CORE_PIN29_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_31  
#define CORE_PIN30_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_37  
#define CORE_PIN31_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_36  
#define CORE_PIN32_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_B0_12   
#define CORE_PIN33_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_07  
#define CORE_PIN34_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B0_03
#define CORE_PIN35_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B0_02
#define CORE_PIN36_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B0_01
#define CORE_PIN37_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B0_00
#define CORE_PIN38_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B0_05
#define CORE_PIN39_PADCONFIG IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B0_04


#define CORE_LED0_PIN 13

#define CORE_ADC0_PIN  14
#define CORE_ADC1_PIN  15
#define CORE_ADC2_PIN  16
#define CORE_ADC3_PIN  17
#define CORE_ADC4_PIN  18
#define CORE_ADC5_PIN  19
#define CORE_ADC6_PIN  20
#define CORE_ADC7_PIN  21
#define CORE_ADC8_PIN  22
#define CORE_ADC9_PIN  23
#define CORE_ADC10_PIN 24
#define CORE_ADC11_PIN 25
#define CORE_ADC12_PIN 26
#define CORE_ADC13_PIN 27


#define CORE_INT0_PIN      0 
#define CORE_INT1_PIN      1 
#define CORE_INT2_PIN      2 
#define CORE_INT3_PIN      3 
#define CORE_INT4_PIN      4 
#define CORE_INT5_PIN      5 
#define CORE_INT6_PIN      6 
#define CORE_INT7_PIN      7 
#define CORE_INT8_PIN      8 
#define CORE_INT9_PIN      9 
#define CORE_INT10_PIN     10
#define CORE_INT11_PIN     11
#define CORE_INT12_PIN     12
#define CORE_INT13_PIN     13
#define CORE_INT14_PIN     14
#define CORE_INT15_PIN     15
#define CORE_INT16_PIN     16
#define CORE_INT17_PIN     17
#define CORE_INT18_PIN     18
#define CORE_INT19_PIN     19
#define CORE_INT20_PIN     20
#define CORE_INT21_PIN     21
#define CORE_INT22_PIN     22
#define CORE_INT23_PIN     23
#define CORE_INT24_PIN     24
#define CORE_INT25_PIN     25
#define CORE_INT26_PIN     26
#define CORE_INT27_PIN     27
#define CORE_INT28_PIN     28
#define CORE_INT29_PIN     29
#define CORE_INT30_PIN     30
#define CORE_INT31_PIN     31
#define CORE_INT32_PIN     32
#define CORE_INT33_PIN     33
#define CORE_INT34_PIN     34
#define CORE_INT35_PIN     35
#define CORE_INT36_PIN     36
#define CORE_INT37_PIN     37
#define CORE_INT38_PIN     38
#define CORE_INT39_PIN     39
#define CORE_INT_EVERY_PIN 1 

#define CORE_NUM_SERIAL_INSTANCES 7

#define SERIAL1_UART_ADDR             IMXRT_LPUART6_ADDRESS          
#define SERIAL1_IRQ                   IRQ_LPUART6                    
#define SERIAL1_CCM_REGISTER          CCM_CCGR3                      
#define SERIAL1_CCM_VALUE             CCM_CCGR3_LPUART6(CCM_CCGR_ON) 
#define SERIAL1_RX_PIN                0                              
#define SERIAL1_RX_MUX_VAL            2                              
#define SERIAL1_RX_INPUT_REGISTER     &IOMUXC_LPUART6_RX_SELECT_INPUT
#define SERIAL1_RX_INPUT_VALUE        1                              
#define SERIAL1_RX_ALT_PIN            0xff                           
#define SERIAL1_RX_ALT_MUX_VAL        0xff                           
#define SERIAL1_RX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL1_RX_ALT_INPUT_VALUE    0                              
#define SERIAL1_TX_PIN                1                              
#define SERIAL1_TX_MUX_VAL            2                              
#define SERIAL1_TX_INPUT_REGISTER     &IOMUXC_LPUART6_TX_SELECT_INPUT
#define SERIAL1_TX_INPUT_VALUE        1                              
#define SERIAL1_TX_ALT_PIN            0xff                           
#define SERIAL1_TX_ALT_MUX_VAL        0xff                           
#define SERIAL1_TX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL1_TX_ALT_INPUT_VALUE    0                              
#define SERIAL1_TX_DMAMUX_SOURCE      DMAMUX_SOURCE_LPUART6_TX       
#define SERIAL1_CTS_PIN               0xff                           
#define SERIAL1_CTS_MUX_VAL           0                              
#define SERIAL1_RTS_LOW_WATERMARK     38                             
#define SERIAL1_RTS_HIGH_WATERMARK    24                             
#define SERIAL1_XBAR_TRIGGER          XBARA1_OUT_LPUART6_TRG_INPUT   

#define SERIAL2_UART_ADDR             IMXRT_LPUART4_ADDRESS          
#define SERIAL2_IRQ                   IRQ_LPUART4                    
#define SERIAL2_CCM_REGISTER          CCM_CCGR1                      
#define SERIAL2_CCM_VALUE             CCM_CCGR1_LPUART4(CCM_CCGR_ON) 
#define SERIAL2_RX_PIN                7                              
#define SERIAL2_RX_MUX_VAL            2                              
#define SERIAL2_RX_INPUT_REGISTER     &IOMUXC_LPUART4_RX_SELECT_INPUT
#define SERIAL2_RX_INPUT_VALUE        2                              
#define SERIAL2_RX_ALT_PIN            0xff                           
#define SERIAL2_RX_ALT_MUX_VAL        0xff                           
#define SERIAL2_RX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL2_RX_ALT_INPUT_VALUE    0                              
#define SERIAL2_TX_PIN                8                              
#define SERIAL2_TX_MUX_VAL            2                              
#define SERIAL2_TX_INPUT_REGISTER     &IOMUXC_LPUART4_TX_SELECT_INPUT
#define SERIAL2_TX_INPUT_VALUE        2                              
#define SERIAL2_TX_ALT_PIN            0xff                           
#define SERIAL2_TX_ALT_MUX_VAL        0xff                           
#define SERIAL2_TX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL2_TX_ALT_INPUT_VALUE    0                              
#define SERIAL2_TX_DMAMUX_SOURCE      DMAMUX_SOURCE_LPUART4_TX       
#define SERIAL2_CTS_PIN               0xff                           
#define SERIAL2_CTS_MUX_VAL           0                              
#define SERIAL2_RTS_LOW_WATERMARK     38                             
#define SERIAL2_RTS_HIGH_WATERMARK    24                             
#define SERIAL2_XBAR_TRIGGER          XBARA1_OUT_LPUART4_TRG_INPUT   

#define SERIAL3_UART_ADDR             IMXRT_LPUART2_ADDRESS          
#define SERIAL3_IRQ                   IRQ_LPUART2                    
#define SERIAL3_CCM_REGISTER          CCM_CCGR0                      
#define SERIAL3_CCM_VALUE             CCM_CCGR0_LPUART2(CCM_CCGR_ON) 
#define SERIAL3_RX_PIN                15                             
#define SERIAL3_RX_MUX_VAL            2                              
#define SERIAL3_RX_INPUT_REGISTER     &IOMUXC_LPUART2_RX_SELECT_INPUT
#define SERIAL3_RX_INPUT_VALUE        1                              
#define SERIAL3_RX_ALT_PIN            0xff                           
#define SERIAL3_RX_ALT_MUX_VAL        0xff                           
#define SERIAL3_RX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL3_RX_ALT_INPUT_VALUE    0                              
#define SERIAL3_TX_PIN                14                             
#define SERIAL3_TX_MUX_VAL            2                              
#define SERIAL3_TX_INPUT_REGISTER     &IOMUXC_LPUART2_TX_SELECT_INPUT
#define SERIAL3_TX_INPUT_VALUE        1                              
#define SERIAL3_TX_ALT_PIN            0xff                           
#define SERIAL3_TX_ALT_MUX_VAL        0xff                           
#define SERIAL3_TX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL3_TX_ALT_INPUT_VALUE    0                              
#define SERIAL3_TX_DMAMUX_SOURCE      DMAMUX_SOURCE_LPUART2_TX       
#define SERIAL3_CTS_PIN               19                             
#define SERIAL3_CTS_MUX_VAL           2                              
#define SERIAL3_RTS_LOW_WATERMARK     38                             
#define SERIAL3_RTS_HIGH_WATERMARK    24                             
#define SERIAL3_XBAR_TRIGGER          XBARA1_OUT_LPUART2_TRG_INPUT   

#define SERIAL4_UART_ADDR             IMXRT_LPUART3_ADDRESS          
#define SERIAL4_IRQ                   IRQ_LPUART3                    
#define SERIAL4_CCM_REGISTER          CCM_CCGR0                      
#define SERIAL4_CCM_VALUE             CCM_CCGR0_LPUART3(CCM_CCGR_ON) 
#define SERIAL4_RX_PIN                16                             
#define SERIAL4_RX_MUX_VAL            2                              
#define SERIAL4_RX_INPUT_REGISTER     &IOMUXC_LPUART3_RX_SELECT_INPUT
#define SERIAL4_RX_INPUT_VALUE        0                              
#define SERIAL4_RX_ALT_PIN            0xff                           
#define SERIAL4_RX_ALT_MUX_VAL        0xff                           
#define SERIAL4_RX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL4_RX_ALT_INPUT_VALUE    0                              
#define SERIAL4_TX_PIN                17                             
#define SERIAL4_TX_MUX_VAL            2                              
#define SERIAL4_TX_INPUT_REGISTER     &IOMUXC_LPUART3_TX_SELECT_INPUT
#define SERIAL4_TX_INPUT_VALUE        0                              
#define SERIAL4_TX_ALT_PIN            0xff                           
#define SERIAL4_TX_ALT_MUX_VAL        0xff                           
#define SERIAL4_TX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL4_TX_ALT_INPUT_VALUE    0                              
#define SERIAL4_TX_DMAMUX_SOURCE      DMAMUX_SOURCE_LPUART3_TX       
#define SERIAL4_CTS_PIN               0xff                           
#define SERIAL4_CTS_MUX_VAL           0                              
#define SERIAL4_RTS_LOW_WATERMARK     38                             
#define SERIAL4_RTS_HIGH_WATERMARK    24                             
#define SERIAL4_XBAR_TRIGGER          XBARA1_OUT_LPUART3_TRG_INPUT   

#define SERIAL5_UART_ADDR             IMXRT_LPUART8_ADDRESS          
#define SERIAL5_IRQ                   IRQ_LPUART8                    
#define SERIAL5_CCM_REGISTER          CCM_CCGR6                      
#define SERIAL5_CCM_VALUE             CCM_CCGR6_LPUART8(CCM_CCGR_ON) 
#define SERIAL5_RX_PIN                21                             
#define SERIAL5_RX_MUX_VAL            2                              
#define SERIAL5_RX_INPUT_REGISTER     &IOMUXC_LPUART8_RX_SELECT_INPUT
#define SERIAL5_RX_INPUT_VALUE        1                              
#define SERIAL5_RX_ALT_PIN            38                             
#define SERIAL5_RX_ALT_MUX_VAL        2                              
#define SERIAL5_RX_ALT_INPUT_REGISTER &IOMUXC_LPUART8_RX_SELECT_INPUT
#define SERIAL5_RX_ALT_INPUT_VALUE    0                              
#define SERIAL5_TX_PIN                20                             
#define SERIAL5_TX_MUX_VAL            2                              
#define SERIAL5_TX_INPUT_REGISTER     &IOMUXC_LPUART8_TX_SELECT_INPUT
#define SERIAL5_TX_INPUT_VALUE        1                              
#define SERIAL5_TX_ALT_PIN            39                             
#define SERIAL5_TX_ALT_MUX_VAL        2                              
#define SERIAL5_TX_ALT_INPUT_REGISTER &IOMUXC_LPUART8_TX_SELECT_INPUT
#define SERIAL5_TX_ALT_INPUT_VALUE    0                              
#define SERIAL5_TX_DMAMUX_SOURCE      DMAMUX_SOURCE_LPUART8_TX       
#define SERIAL5_CTS_PIN               35                             
#define SERIAL5_CTS_MUX_VAL           2                              
#define SERIAL5_RTS_LOW_WATERMARK     38                             
#define SERIAL5_RTS_HIGH_WATERMARK    24                             
#define SERIAL5_XBAR_TRIGGER          XBARA1_OUT_LPUART8_TRG_INPUT   

#define SERIAL6_UART_ADDR             IMXRT_LPUART1_ADDRESS         
#define SERIAL6_IRQ                   IRQ_LPUART1                   
#define SERIAL6_CCM_REGISTER          CCM_CCGR5                     
#define SERIAL6_CCM_VALUE             CCM_CCGR5_LPUART1(CCM_CCGR_ON)
#define SERIAL6_RX_PIN                25                            
#define SERIAL6_RX_MUX_VAL            2                             
#define SERIAL6_RX_INPUT_REGISTER     nullptr                       
#define SERIAL6_RX_INPUT_VALUE        0                             
#define SERIAL6_RX_ALT_PIN            0xff                          
#define SERIAL6_RX_ALT_MUX_VAL        0xff                          
#define SERIAL6_RX_ALT_INPUT_REGISTER nullptr                       
#define SERIAL6_RX_ALT_INPUT_VALUE    0                             
#define SERIAL6_TX_PIN                24                            
#define SERIAL6_TX_MUX_VAL            2                             
#define SERIAL6_TX_INPUT_REGISTER     nullptr                       
#define SERIAL6_TX_INPUT_VALUE        0                             
#define SERIAL6_TX_ALT_PIN            0xff                          
#define SERIAL6_TX_ALT_MUX_VAL        0xff                          
#define SERIAL6_TX_ALT_INPUT_REGISTER nullptr                       
#define SERIAL6_TX_ALT_INPUT_VALUE    0                             
#define SERIAL6_TX_DMAMUX_SOURCE      DMAMUX_SOURCE_LPUART1_TX      
#define SERIAL6_CTS_PIN               0xff                          
#define SERIAL6_CTS_MUX_VAL           0                             
#define SERIAL6_RTS_LOW_WATERMARK     38                            
#define SERIAL6_RTS_HIGH_WATERMARK    24                            
#define SERIAL6_XBAR_TRIGGER          XBARA1_OUT_LPUART1_TRG_INPUT  

#define SERIAL7_UART_ADDR             IMXRT_LPUART7_ADDRESS          
#define SERIAL7_IRQ                   IRQ_LPUART7                    
#define SERIAL7_CCM_REGISTER          CCM_CCGR5                      
#define SERIAL7_CCM_VALUE             CCM_CCGR5_LPUART7(CCM_CCGR_ON) 
#define SERIAL7_RX_PIN                28                             
#define SERIAL7_RX_MUX_VAL            2                              
#define SERIAL7_RX_INPUT_REGISTER     &IOMUXC_LPUART7_RX_SELECT_INPUT
#define SERIAL7_RX_INPUT_VALUE        1                              
#define SERIAL7_RX_ALT_PIN            0xff                           
#define SERIAL7_RX_ALT_MUX_VAL        0xff                           
#define SERIAL7_RX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL7_RX_ALT_INPUT_VALUE    0                              
#define SERIAL7_TX_PIN                29                             
#define SERIAL7_TX_MUX_VAL            2                              
#define SERIAL7_TX_INPUT_REGISTER     &IOMUXC_LPUART7_TX_SELECT_INPUT
#define SERIAL7_TX_INPUT_VALUE        1                              
#define SERIAL7_TX_ALT_PIN            0xff                           
#define SERIAL7_TX_ALT_MUX_VAL        0xff                           
#define SERIAL7_TX_ALT_INPUT_REGISTER nullptr                        
#define SERIAL7_TX_ALT_INPUT_VALUE    0                              
#define SERIAL7_TX_DMAMUX_SOURCE      DMAMUX_SOURCE_LPUART7_TX       
#define SERIAL7_CTS_PIN               0xff                           
#define SERIAL7_CTS_MUX_VAL           0                              
#define SERIAL7_RTS_LOW_WATERMARK     38                             
#define SERIAL7_RTS_HIGH_WATERMARK    24                             
#define SERIAL7_XBAR_TRIGGER          XBARA1_OUT_LPUART7_TRG_INPUT   

// used in cores/digital.c for `digital_pin_to_info_PGM[]`
#define PINS_TO_DIGITAL_INFO {                                                          \
  {&CORE_PIN0_PORTREG, &CORE_PIN0_CONFIG, &CORE_PIN0_PADCONFIG, CORE_PIN0_BITMASK},     \
  {&CORE_PIN1_PORTREG, &CORE_PIN1_CONFIG, &CORE_PIN1_PADCONFIG, CORE_PIN1_BITMASK},     \
  {&CORE_PIN2_PORTREG, &CORE_PIN2_CONFIG, &CORE_PIN2_PADCONFIG, CORE_PIN2_BITMASK},     \
  {&CORE_PIN3_PORTREG, &CORE_PIN3_CONFIG, &CORE_PIN3_PADCONFIG, CORE_PIN3_BITMASK},     \
  {&CORE_PIN4_PORTREG, &CORE_PIN4_CONFIG, &CORE_PIN4_PADCONFIG, CORE_PIN4_BITMASK},     \
  {&CORE_PIN5_PORTREG, &CORE_PIN5_CONFIG, &CORE_PIN5_PADCONFIG, CORE_PIN5_BITMASK},     \
  {&CORE_PIN6_PORTREG, &CORE_PIN6_CONFIG, &CORE_PIN6_PADCONFIG, CORE_PIN6_BITMASK},     \
  {&CORE_PIN7_PORTREG, &CORE_PIN7_CONFIG, &CORE_PIN7_PADCONFIG, CORE_PIN7_BITMASK},     \
  {&CORE_PIN8_PORTREG, &CORE_PIN8_CONFIG, &CORE_PIN8_PADCONFIG, CORE_PIN8_BITMASK},     \
  {&CORE_PIN9_PORTREG, &CORE_PIN9_CONFIG, &CORE_PIN9_PADCONFIG, CORE_PIN9_BITMASK},     \
  {&CORE_PIN10_PORTREG, &CORE_PIN10_CONFIG, &CORE_PIN10_PADCONFIG, CORE_PIN10_BITMASK}, \
  {&CORE_PIN11_PORTREG, &CORE_PIN11_CONFIG, &CORE_PIN11_PADCONFIG, CORE_PIN11_BITMASK}, \
  {&CORE_PIN12_PORTREG, &CORE_PIN12_CONFIG, &CORE_PIN12_PADCONFIG, CORE_PIN12_BITMASK}, \
  {&CORE_PIN13_PORTREG, &CORE_PIN13_CONFIG, &CORE_PIN13_PADCONFIG, CORE_PIN13_BITMASK}, \
  {&CORE_PIN14_PORTREG, &CORE_PIN14_CONFIG, &CORE_PIN14_PADCONFIG, CORE_PIN14_BITMASK}, \
  {&CORE_PIN15_PORTREG, &CORE_PIN15_CONFIG, &CORE_PIN15_PADCONFIG, CORE_PIN15_BITMASK}, \
  {&CORE_PIN16_PORTREG, &CORE_PIN16_CONFIG, &CORE_PIN16_PADCONFIG, CORE_PIN16_BITMASK}, \
  {&CORE_PIN17_PORTREG, &CORE_PIN17_CONFIG, &CORE_PIN17_PADCONFIG, CORE_PIN17_BITMASK}, \
  {&CORE_PIN18_PORTREG, &CORE_PIN18_CONFIG, &CORE_PIN18_PADCONFIG, CORE_PIN18_BITMASK}, \
  {&CORE_PIN19_PORTREG, &CORE_PIN19_CONFIG, &CORE_PIN19_PADCONFIG, CORE_PIN19_BITMASK}, \
  {&CORE_PIN20_PORTREG, &CORE_PIN20_CONFIG, &CORE_PIN20_PADCONFIG, CORE_PIN20_BITMASK}, \
  {&CORE_PIN21_PORTREG, &CORE_PIN21_CONFIG, &CORE_PIN21_PADCONFIG, CORE_PIN21_BITMASK}, \
  {&CORE_PIN22_PORTREG, &CORE_PIN22_CONFIG, &CORE_PIN22_PADCONFIG, CORE_PIN22_BITMASK}, \
  {&CORE_PIN23_PORTREG, &CORE_PIN23_CONFIG, &CORE_PIN23_PADCONFIG, CORE_PIN23_BITMASK}, \
  {&CORE_PIN24_PORTREG, &CORE_PIN24_CONFIG, &CORE_PIN24_PADCONFIG, CORE_PIN24_BITMASK}, \
  {&CORE_PIN25_PORTREG, &CORE_PIN25_CONFIG, &CORE_PIN25_PADCONFIG, CORE_PIN25_BITMASK}, \
  {&CORE_PIN26_PORTREG, &CORE_PIN26_CONFIG, &CORE_PIN26_PADCONFIG, CORE_PIN26_BITMASK}, \
  {&CORE_PIN27_PORTREG, &CORE_PIN27_CONFIG, &CORE_PIN27_PADCONFIG, CORE_PIN27_BITMASK}, \
  {&CORE_PIN28_PORTREG, &CORE_PIN28_CONFIG, &CORE_PIN28_PADCONFIG, CORE_PIN28_BITMASK}, \
  {&CORE_PIN29_PORTREG, &CORE_PIN29_CONFIG, &CORE_PIN29_PADCONFIG, CORE_PIN29_BITMASK}, \
  {&CORE_PIN30_PORTREG, &CORE_PIN30_CONFIG, &CORE_PIN30_PADCONFIG, CORE_PIN30_BITMASK}, \
  {&CORE_PIN31_PORTREG, &CORE_PIN31_CONFIG, &CORE_PIN31_PADCONFIG, CORE_PIN31_BITMASK}, \
  {&CORE_PIN32_PORTREG, &CORE_PIN32_CONFIG, &CORE_PIN32_PADCONFIG, CORE_PIN32_BITMASK}, \
  {&CORE_PIN33_PORTREG, &CORE_PIN33_CONFIG, &CORE_PIN33_PADCONFIG, CORE_PIN33_BITMASK}, \
  {&CORE_PIN34_PORTREG, &CORE_PIN34_CONFIG, &CORE_PIN34_PADCONFIG, CORE_PIN34_BITMASK}, \
  {&CORE_PIN35_PORTREG, &CORE_PIN35_CONFIG, &CORE_PIN35_PADCONFIG, CORE_PIN35_BITMASK}, \
  {&CORE_PIN36_PORTREG, &CORE_PIN36_CONFIG, &CORE_PIN36_PADCONFIG, CORE_PIN36_BITMASK}, \
  {&CORE_PIN37_PORTREG, &CORE_PIN37_CONFIG, &CORE_PIN37_PADCONFIG, CORE_PIN37_BITMASK}, \
  {&CORE_PIN38_PORTREG, &CORE_PIN38_CONFIG, &CORE_PIN38_PADCONFIG, CORE_PIN38_BITMASK}, \
  {&CORE_PIN39_PORTREG, &CORE_PIN39_CONFIG, &CORE_PIN39_PADCONFIG, CORE_PIN39_BITMASK}, \
}

// used in cores/analog.c for `pin_to_channel[]`
#define PINS_TO_ANALOG_CHANNELS {         \
  255,   /* 0  -         GPIO_AD_B0_03 */ \
  255,   /* 1  -         GPIO_AD_B0_02 */ \
  255,   /* 2  -         GPIO_EMC_04   */ \
  255,   /* 3  -         GPIO_EMC_05   */ \
  255,   /* 4  -         GPIO_EMC_06   */ \
  255,   /* 5  -         GPIO_EMC_08   */ \
  255,   /* 6  -         GPIO_B0_10    */ \
  255,   /* 7  -         GPIO_B1_01    */ \
  255,   /* 8  -         GPIO_B1_00    */ \
  255,   /* 9  -         GPIO_B0_11    */ \
  255,   /* 10 -         GPIO_B0_00    */ \
  255,   /* 11 -         GPIO_B0_02    */ \
  255,   /* 12 -         GPIO_B0_01    */ \
  255,   /* 13 -         GPIO_B0_03    */ \
  7,     /* 14 ADC1_IN7  GPIO_AD_B1_02 */ \
  8,     /* 15 ADC1_IN8  GPIO_AD_B1_03 */ \
  12,    /* 16 ADC1_IN12 GPIO_AD_B1_07 */ \
  11,    /* 17 ADC1_IN11 GPIO_AD_B1_06 */ \
  6,     /* 18 ADC1_IN6  GPIO_AD_B1_01 */ \
  5,     /* 19 ADC1_IN5  GPIO_AD_B1_00 */ \
  15,    /* 20 ADC1_IN15 GPIO_AD_B1_10 */ \
  0,     /* 21 ADC1_IN0  GPIO_AD_B1_11 */ \
  13,    /* 22 ADC1_IN13 GPIO_AD_B1_08 */ \
  14,    /* 23 ADC1_IN14 GPIO_AD_B1_09 */ \
  1,     /* 24 ADC1_IN1  GPIO_AD_B0_12 */ \
  2,     /* 25 ADC1_IN2  GPIO_AD_B0_13 */ \
  128+3, /* 26 ADC2_IN3  GPIO_AD_B1_14 */ \
  128+4, /* 27 ADC2_IN4  GPIO_AD_B1_15 */ \
}

#define M(a, b) ((((a) - 1) << 4) | (b))

// used in cores/pwm.c for `pwm_pin_info[]`
#define PINS_TO_PWM_INFO {                     \
  {1, M(1, 1), 0, 4}, /* 0  FLEXPWM1_PWMX01 */ \
  {1, M(1, 0), 0, 4}, /* 1  FLEXPWM1_PWMX00 */ \
  {1, M(4, 2), 1, 1}, /* 2  FLEXPWM4_PWMA02 */ \
  {1, M(4, 2), 2, 1}, /* 3  FLEXPWM4_PWMB02 */ \
  {1, M(2, 0), 1, 1}, /* 4  FLEXPWM2_PWMA00 */ \
  {1, M(2, 1), 1, 1}, /* 5  FLEXPWM2_PWMA01 */ \
  {1, M(2, 2), 1, 2}, /* 6  FLEXPWM2_PWMA02 */ \
  {1, M(1, 3), 2, 6}, /* 7  FLEXPWM1_PWMB03 */ \
  {1, M(1, 3), 1, 6}, /* 8  FLEXPWM1_PWMA03 */ \
  {1, M(2, 2), 2, 2}, /* 9  FLEXPWM2_PWMB02 */ \
  {2, M(1, 0), 0, 1}, /* 10 QTIMER1_TIMER0  */ \
  {2, M(1, 2), 0, 1}, /* 11 QTIMER1_TIMER2  */ \
  {2, M(1, 1), 0, 1}, /* 12 QTIMER1_TIMER1  */ \
  {2, M(2, 0), 0, 1}, /* 13 QTIMER2_TIMER0  */ \
  {2, M(3, 2), 0, 1}, /* 14 QTIMER3_TIMER2  */ \
  {2, M(3, 3), 0, 1}, /* 15 QTIMER3_TIMER3  */ \
  {0, M(1, 0), 0, 0}, /* 16 -               */ \
  {0, M(1, 0), 0, 0}, /* 17 -               */ \
  {2, M(3, 1), 0, 1}, /* 18 QTIMER3_TIMER1  */ \
  {2, M(3, 0), 0, 1}, /* 19 QTIMER3_TIMER0  */ \
  {0, M(1, 0), 0, 0}, /* 20 -               */ \
  {0, M(1, 0), 0, 0}, /* 21 -               */ \
  {1, M(4, 0), 1, 1}, /* 22 FLEXPWM4_PWMA00 */ \
  {1, M(4, 1), 1, 1}, /* 23 FLEXPWM4_PWMA01 */ \
  {1, M(1, 2), 0, 4}, /* 24 FLEXPWM1_PWMX02 */ \
  {1, M(1, 3), 0, 4}, /* 25 FLEXPWM1_PWMX03 */ \
  {0, M(1, 0), 0, 0}, /* 26 -               */ \
  {0, M(1, 0), 0, 0}, /* 27 -               */ \
  {1, M(3, 1), 2, 1}, /* 28 FLEXPWM3_PWMB01 */ \
  {1, M(3, 1), 1, 1}, /* 29 FLEXPWM3_PWMA01 */ \
  {0, M(1, 0), 0, 0}, /* 30 -               */ \
  {0, M(1, 0), 0, 0}, /* 31 -               */ \
  {0, M(1, 0), 0, 0}, /* 32 -               */ \
  {1, M(2, 0), 2, 1}, /* 33 FLEXPWM2_PWMB00 */ \
  {1, M(1, 1), 2, 1}, /* 34 FLEXPWM1_PWMB01 */ \
  {1, M(1, 1), 1, 1}, /* 35 FLEXPWM1_PWMA01 */ \
  {1, M(1, 0), 2, 1}, /* 36 FLEXPWM1_PWMB00 */ \
  {1, M(1, 0), 1, 1}, /* 37 FLEXPWM1_PWMA00 */ \
  {1, M(1, 2), 2, 1}, /* 38 FLEXPWM1_PWMB02 */ \
  {1, M(1, 2), 1, 1}, /* 39 FLEXPWM1_PWMA02 */ \
}

// used in cores/HardwareSerial.cpp for `pin_to_xbar_info[]`
#define PINS_TO_XBAR_INFO {                          \
  { 0, 17, 1, &IOMUXC_XBAR1_IN17_SELECT_INPUT, 0x1}, \
  { 1, 16, 1, nullptr, 0  },                         \
  { 2,  6, 3, &IOMUXC_XBAR1_IN06_SELECT_INPUT, 0x0}, \
  { 3,  7, 3, &IOMUXC_XBAR1_IN07_SELECT_INPUT, 0x0}, \
  { 4,  8, 3, &IOMUXC_XBAR1_IN08_SELECT_INPUT, 0x0}, \
  { 5, 17, 3, &IOMUXC_XBAR1_IN17_SELECT_INPUT, 0x0}, \
  { 7, 15, 1, &IOMUXC_XBAR1_IN15_SELECT_INPUT, 0x1}, \
  { 8, 14, 1, &IOMUXC_XBAR1_IN14_SELECT_INPUT, 0x1}, \
  {30, 23, 1, &IOMUXC_XBAR1_IN23_SELECT_INPUT, 0x0}, \
  {31, 22, 1, &IOMUXC_XBAR1_IN22_SELECT_INPUT, 0x0}, \
  {32, 10, 1, nullptr, 0  },                         \
  {33,  9, 3, &IOMUXC_XBAR1_IN09_SELECT_INPUT, 0x0}, \
  {34,  7, 3, &IOMUXC_XBAR1_IN07_SELECT_INPUT, 0x1}, \
  {35,  6, 3, &IOMUXC_XBAR1_IN06_SELECT_INPUT, 0x1}, \
  {36,  5, 3, &IOMUXC_XBAR1_IN05_SELECT_INPUT, 0x1}, \
  {37,  4, 3, &IOMUXC_XBAR1_IN04_SELECT_INPUT, 0x1}, \
  {38,  9, 3, &IOMUXC_XBAR1_IN09_SELECT_INPUT, 0x1}, \
  {39,  8, 3, &IOMUXC_XBAR1_IN08_SELECT_INPUT, 0x1}, \
};
